# Service name
spring.application.name=production-service

## PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/productiondb
spring.datasource.username=postgres
spring.datasource.password=postgres

## JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


